---
- set_fact:
    load_balancer_name: "{{ dict() }}"

- { include: create/load-balancer.yml, system_role: application, when: "load_balancers_enabled and environment_tier in ['staging', 'production'] and 'application' in required_systems"}
- { include: create/load-balancer.yml, system_role: database,    when: "load_balancers_enabled and environment_tier in ['staging', 'production'] and 'database' in required_systems" }
- { include: create/load-balancer.yml, system_role: outbound,    when: "load_balancers_enabled and environment_tier in ['staging', 'production'] and 'outbound' in required_systems" }
